### ISSUE TITLE
SNI is not supported.

### ISSUE THREAD

**Issue by jwoll** [sapcc/nova-password#6]
When specifying a domain name, I receive the following error : 

2020/03/03 10:12:20 [DEBUG] OpenStack connection error, retries exhausted. Aborting
Error: Post https://URLREMOVED: OpenStack connection error, retries exhausted. Aborting. Last error was: x509: certificate signed by unknown authority

**Comment by kayrus** [comment]
@jwoll could you please provide more details on how to reproduce your issue? Do you try to use nova-password against openstack endpoint with a self-signed certificate?

**Comment by jwoll** [comment]
The certificate for the endpoint is not self-signed.

I'm using version 0.4 and am simply trying to retrieve the password from the instance via the instance ID.

My openrc file is configured in the .zshrc config.

The command I'm entering is : 

`sudo ./nova-password instanceid -i ~/.ssh/id_rsa -d`

Then it comes back with that error.

Theres not much else to say. :-D

**Comment by kayrus** [comment]
@jwoll this is definitely not an SNI issue. Golang detects that this certificate is not trusted. Nevertheless, I released a new version, where you can explicitly disable TLS certificate validation (**not recommended**), or provide a path to a CA, that signed an endpoint certificate.

**Comment by jwoll** [comment]
Hey @kayrus , how do you disable the TLS cert validation? I'm not seeing it on the documentation. I'm still receiving this error with v5. Thank you.
